### ISSUE TITLE
Leveling up skill takes 50 levels no matter how high the user's level is

### ISSUE THREAD

**Issue by ValMobile** [mVabo/EnhancedSurvival#7]
Leveling up skill takes 50 levels no matter how high the user's level is. It should scale with the amount of xp the person has. For example, it should take maybe 30 levels away from a person who 100 xp levels instead of the full 50.

**Comment by mVabo** [comment]
It is ment to be that high because this is an extension to the normal gameplay and after lvl 30 (normal max enchant) this is what you can reach for next.
